# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hunge Labs
email: tesseraskye@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  An open-source and colaboratively written specialty coffee wiki built with love by the community of James Hoffmann's discord.
baseurl: ""
url: "https://hungelabs.github.io"
repository: "hungelabs/hungelabs.github.io"
logo: "/assets/images/SproTransHigh.png"
github_username:  hungelabs
search: true
og_image: /assets/images/SproDarkBKGSmall.png
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"

# Build settings

minimal_mistakes_skin: "dark"

plugins:
  - jekyll-feed
  - jekyll-include-cache

#Includes
include: ["wiki"]

# DEFAULTS N SHIT!
defaults:
  #blog posts n shit
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: "single"
  #wiki pages
  - scope:
      path: "wiki/*/*/*"
      type: pages
    values:
      layout: single

  #posts