title: Hunge Labs
email: tesseraskye@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  An open-source and colaboratively written specialty coffee wiki built with love by the community of James Hoffmann's discord.
baseurl: ""
url: "https://hungelabs.github.io"
repository: "hungelabs/hungelabs.github.io"
logo: "/assets/images/SproTransHigh.png"
github_username:  hungelabs
search: true
og_image: /assets/images/SproDarkBKGSmall.png
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Build settings

minimal_mistakes_skin: "dark"

plugins:
  - jekyll-feed
  - jekyll-include-cache

###
#COLLECTIONS
###
collections_dir: wiki
collections:
  knowledgebase:
    output: true
  equipment:
    output: true
  meta:
    output: true

# DEFAULTS N SHIT!
defaults:
  #blog posts n shit
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      show_date: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      page_excerpts: true
  #catigory default
  - scope:
      path: ""
      type: "knowledgebase"
    values:
      layout: wiki
      page_excerpts: true
      toc: true
      toc_sticky: true
      breadcrumbs: true
  - scope:
      path: ""
      type: "equipment"
    values:
      layout: wiki
      page_excerpts: true
      toc: true
      toc_sticky: true
      breadcrumbs: true
  - scope:
      path: ""
      type: "meta"
    values:
      layout: wiki
      page_excerpts: true
      toc: true
      toc_sticky: true
      breadcrumbs: true

  #posts