name: Build Preview

permissions:
  contents: write
  pull-requests: write

on: 
  pull_request:
      types:
        - opened
        - reopened
        - synchronize
        - closed

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    concurrency: preview-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy Preview
        uses: hungelabs/pr-preview-action@main
        with: 
          source-dir: ./public
          umbrella-dir: preview