name: Publish Site

permissions:
  contents: write

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy-prod:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy to Prod
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./public
          git-config-name: 'github-actions[bot]'
          git-config-email: 'github-actions[bot]@users.noreply.github.com'
          force: false
          clean-exclude: preview
